spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    ## test4
    #    url: jdbc:mysql://localhost:9966/oryx_workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&&autoReconnect=true&failOverReadOnly=false
    ## test3
    url: jdbc:mysql://localhost:3306/oxy_education?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&&autoReconnect=true&failOverReadOnly=false


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


education-common:
  aspect:
    enabled: true
  methodLog:
    enabled: true
  webLog:
    enabled: true






